name: ML-labeling
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - netcdf4
  - cartopy
  - jupyter
  - xarray
  - cfgrib
  - pandas
  - geopandas
  - metpy
  - pip
  - pip:
    - cdsapi
