name: ML-clustering
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - netcdf4
  - cartopy
  - jupyter
  - conda-build
  - xarray
  - cfgrib
  - pandas
  - geopandas
  - libpysal
  - pip
  - pip:
